config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                                      Controller#Action
#         new_user_session GET    /users/sign_in(.:format)                         devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                         devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                        devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)                    devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)                   devise/passwords#edit
#            user_password PATCH  /users/password(.:format)                        devise/passwords#update
#                          PUT    /users/password(.:format)                        devise/passwords#update
#                          POST   /users/password(.:format)                        devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)                          devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)                         devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                            devise/registrations#edit
#        user_registration PATCH  /users(.:format)                                 devise/registrations#update
#                          PUT    /users(.:format)                                 devise/registrations#update
#                          DELETE /users(.:format)                                 devise/registrations#destroy
#                          POST   /users(.:format)                                 devise/registrations#create
#           quiz_questions GET    /quizzes/:quiz_id/questions(.:format)            questions#index
#                          POST   /quizzes/:quiz_id/questions(.:format)            questions#create
#        new_quiz_question GET    /quizzes/:quiz_id/questions/new(.:format)        questions#new
#       edit_quiz_question GET    /quizzes/:quiz_id/questions/:id/edit(.:format)   questions#edit
#            quiz_question GET    /quizzes/:quiz_id/questions/:id(.:format)        questions#show
#                          PATCH  /quizzes/:quiz_id/questions/:id(.:format)        questions#update
#                          PUT    /quizzes/:quiz_id/questions/:id(.:format)        questions#update
#                          DELETE /quizzes/:quiz_id/questions/:id(.:format)        questions#destroy
#         quiz_submissions POST   /quizzes/:quiz_id/quiz_submissions(.:format)     quiz_submissions#create
#          quiz_submission GET    /quizzes/:quiz_id/quiz_submissions/:id(.:format) quiz_submissions#show
#                  quizzes GET    /quizzes(.:format)                               quizzes#index
#                          POST   /quizzes(.:format)                               quizzes#create
#                 new_quiz GET    /quizzes/new(.:format)                           quizzes#new
#                edit_quiz GET    /quizzes/:id/edit(.:format)                      quizzes#edit
#                     quiz GET    /quizzes/:id(.:format)                           quizzes#show
#                          PATCH  /quizzes/:id(.:format)                           quizzes#update
#                          PUT    /quizzes/:id(.:format)                           quizzes#update
#                          DELETE /quizzes/:id(.:format)                           quizzes#destroy
#                     root GET    /                                                quizzes#index

Rails.application.routes.draw do
  get 'quiz_submissions/create'
  get 'quiz_submissions/show'
  devise_for :users
  resources :quizzes do
    resources :questions
    resources :quiz_submissions, only: [:show, :create], as: "submissions"
  end
  root "quizzes#index"
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: %i[ show edit update destroy ]

  # GET /quizzes
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1
  def show; end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
    # create the first question
    @quiz.questions.build
  end

  # GET /quizzes/1/edit
  def edit; end

  # POST /quizzes
  def create
    @quiz = Quiz.new(quiz_params)

    if @quiz.save
      redirect_to @quiz, notice: "Quiz was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /quizzes/1
  def update
    if @quiz.update(quiz_params)
      redirect_to @quiz, notice: "Quiz was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /quizzes/1
  def destroy
    @quiz.destroy
    redirect_to quizzes_url, notice: "Quiz was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_quiz
    @quiz = Quiz.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def quiz_params
    params.require(:quiz).permit(
      :title,
      :image,
      question_attributes: [:id, :_destroy, :content, :answer1, :answer2, :answer3, :answer4, :correct_answer, :image]
    )
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<%= form_with(model: quiz) do |form| %>
  <% if quiz.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
        <% quiz.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/quizzes/_quiz.html.erb
<div id="<%= dom_id quiz %>">
  <p>
    <strong>Title:</strong>
    <%= quiz.title %>
  </p>

</div>

app/views/quizzes/edit.html.erb
<h1>Editing quiz</h1>

<%= render "form", quiz: @quiz %>

<br>

<div>
  <%= link_to "Show this quiz", @quiz %> |
  <%= link_to "Back to quizzes", quizzes_path %>
</div>

app/views/quizzes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Quizzes</h1>

<div id="quizzes">
  <% @quizzes.each do |quiz| %>
    <%= render quiz %>
    <p>
      <%= link_to "Show this quiz", quiz %>
    </p>
  <% end %>
</div>

<%= link_to "New quiz", new_quiz_path %>

app/views/quizzes/new.html.erb
<h1>New quiz</h1>

<%= render "form", quiz: @quiz %>

<br>

<div>
  <%= link_to "Back to quizzes", quizzes_path %>
</div>

app/views/quizzes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @quiz %>

<div>
  <%= link_to "Edit this quiz", edit_quiz_path(@quiz) %> |
  <%= link_to "Back to quizzes", quizzes_path %>

  <%= button_to "Destroy this quiz", @quiz, method: :delete %>
</div>